name: Multi Docker Image Build and Push to ECR

on:
  push:
    branches:
      - compose-dhlee

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: 소스코드 체크아웃
        uses: actions/checkout@v4

      - name: AWS 인증 정보 등록
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: ECR 로그인
        uses: aws-actions/amazon-ecr-login@v2

      - name: 여러 서비스 도커 이미지 빌드 & 푸시
        env:
          ECR_REGISTRY: 221082190600.dkr.ecr.ap-northeast-2.amazonaws.com
        run: |
          SERVICES="config-service discovery-service gateway-service point-service restaurant-service review-service user-service"
          for SERVICE in $SERVICES; do
            echo "===== $SERVICE 빌드 및 푸시 시작 ====="
            docker build -t $SERVICE:${GITHUB_SHA} ./back/$SERVICE
            docker tag $SERVICE:${GITHUB_SHA} $ECR_REGISTRY/$SERVICE:${GITHUB_SHA}
            docker tag $SERVICE:${GITHUB_SHA} $ECR_REGISTRY/$SERVICE:latest
            docker push $ECR_REGISTRY/$SERVICE:${GITHUB_SHA}
            docker push $ECR_REGISTRY/$SERVICE:latest
            echo "===== $SERVICE 푸시 완료 ====="
          done

      - name: Config Service application-dev.yml 주입
        uses: appleboy/ssh-action@v1.0.3
        with:
          host:     ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key:      ${{ secrets.EC2_SSH_KEY }}
          script: |
            mkdir -p /home/ubuntu/config-service-tmp
            cat << 'EOF' > /home/ubuntu/config-service-tmp/application-dev.yml
            ${{ secrets.CONFIG_SERVICE_DEV_YML }}
            EOF

      - name: EC2에서 ECR 로그인
        uses: appleboy/ssh-action@v1.0.3
        with:
          host:     ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key:      ${{ secrets.EC2_SSH_KEY }}
          script: |
            aws ecr get-login-password --region ap-northeast-2 \
              | docker login --username AWS --password-stdin 221082190600.dkr.ecr.ap-northeast-2.amazonaws.com

      - name: 전체 서비스 docker-compose로 재배포
        uses: appleboy/ssh-action@v1.0.3
        with:
          host:     ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key:      ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/reviewing-msa/back    # docker-compose.yml 위치로 이동
            docker-compose pull
            docker-compose down
            docker-compose up -d

            # (선택) 상태 확인
            docker-compose ps
